## https://github.com/dessant/lock-threads
name: "Lock Threads"
description: "Lock Threads is a GitHub Action that locks closed issues, pull requests and discussions after a period of inactivity."
branding:
  icon: "lock"
  color: "gray-dark"

inputs:
  ## from https://github.com/dessant/lock-threads/blob/main/action.yml
  ## allow the full list of options here, accepted as inputs with some modified defaults
  github-token:
    description: "GitHub access token"
    default: "${{ github.token }}"
  issue-inactive-days:
    description: "Number of days of inactivity before a closed issue is locked"
    default: "30"
  exclude-issue-created-before:
    description: "Do not lock issues created before a given date, value must follow ISO 8601"
    default: ""
  exclude-issue-created-after:
    description: "Do not lock issues created after a given date, value must follow ISO 8601"
    default: ""
  exclude-issue-created-between:
    description: "Do not lock issues created in a given time interval, value must follow ISO 8601"
    default: ""
  exclude-issue-closed-before:
    description: "Do not lock issues closed before a given date, value must follow ISO 8601"
    default: ""
  exclude-issue-closed-after:
    description: "Do not lock issues closed after a given date, value must follow ISO 8601"
    default: ""
  exclude-issue-closed-between:
    description: "Do not lock issues closed in a given time interval, value must follow ISO 8601"
    default: ""
  include-any-issue-labels:
    description: "Only lock issues with any of these labels, value must be a comma separated list of labels"
    default: ""
  include-all-issue-labels:
    description: "Only lock issues with all these labels, value must be a comma separated list of labels"
    default: ""
  exclude-any-issue-labels:
    description: "Do not lock issues with any of these labels, value must be a comma separated list of labels"
    default: ""
  add-issue-labels:
    description: "Labels to add before locking an issue, value must be a comma separated list of labels"
    default: "locked"
  remove-issue-labels:
    description: "Labels to remove before locking an issue, value must be a comma separated list of labels"
    default: ""
  issue-comment:
    description: "Comment to post before locking an issue"
    default: >
      This issue has been automatically locked since there
      has not been any recent activity after it was closed.
      Please open a new issue for related bugs.
  issue-lock-reason:
    description: "Reason for locking an issue, value must be one of `resolved`, `off-topic`, `too heated` or `spam`"
    default: "resolved"
  pr-inactive-days:
    description: "Number of days of inactivity before a closed pull request is locked"
    default: "30"
  exclude-pr-created-before:
    description: "Do not lock pull requests created before a given date, value must follow ISO 8601"
    default: ""
  exclude-pr-created-after:
    description: "Do not lock pull requests created after a given date, value must follow ISO 8601"
    default: ""
  exclude-pr-created-between:
    description: "Do not lock pull requests created in a given time interval, value must follow ISO 8601"
    default: ""
  exclude-pr-closed-before:
    description: "Do not lock pull requests closed before a given date, value must follow ISO 8601"
    default: ""
  exclude-pr-closed-after:
    description: "Do not lock pull requests closed after a given date, value must follow ISO 8601"
    default: ""
  exclude-pr-closed-between:
    description: "Do not lock pull requests closed in a given time interval, value must follow ISO 8601"
    default: ""
  include-any-pr-labels:
    description: "Only lock pull requests with any of these labels, value must be a comma separated list of labels"
    default: ""
  include-all-pr-labels:
    description: "Only lock pull requests with all these labels, value must be a comma separated list of labels"
    default: ""
  exclude-any-pr-labels:
    description: "Do not lock pull requests with any of these labels, value must be a comma separated list of labels"
    default: ""
  add-pr-labels:
    description: "Labels to add before locking a pull request, value must be a comma separated list of labels"
    default: "locked"
  remove-pr-labels:
    description: "Labels to remove before locking a pull request, value must be a comma separated list of labels"
    default: ""
  pr-comment:
    description: "Comment to post before locking a pull request"
    default: >
      This pull request has been automatically locked since there
      has not been any recent activity after it was closed.
      Please open a new issue for related bugs.
  pr-lock-reason:
    description: "Reason for locking a pull request, value must be one of `resolved`, `off-topic`, `too heated` or `spam`"
    default: "resolved"
  discussion-inactive-days:
    description: "Number of days of inactivity before a closed discussion is locked"
    default: "365"
  exclude-discussion-created-before:
    description: "Do not lock discussions created before a given date, value must follow ISO 8601"
    default: ""
  exclude-discussion-created-after:
    description: "Do not lock discussions created after a given date, value must follow ISO 8601"
    default: ""
  exclude-discussion-created-between:
    description: "Do not lock discussions created in a given time interval, value must follow ISO 8601"
    default: ""
  exclude-discussion-closed-before:
    description: "Do not lock discussions closed before a given date, value must follow ISO 8601"
    default: ""
  exclude-discussion-closed-after:
    description: "Do not lock discussions closed after a given date, value must follow ISO 8601"
    default: ""
  exclude-discussion-closed-between:
    description: "Do not lock discussions closed in a given time interval, value must follow ISO 8601"
    default: ""
  include-any-discussion-labels:
    description: "Only lock issues with any of these labels, value must be a comma separated list of labels"
    default: ""
  include-all-discussion-labels:
    description: "Only lock discussions with all these labels, value must be a comma separated list of labels"
    default: ""
  exclude-any-discussion-labels:
    description: "Do not lock discussions with any of these labels, value must be a comma separated list of labels"
    default: ""
  add-discussion-labels:
    description: "Labels to add before locking a discussion, value must be a comma separated list of labels"
    default: "locked"
  remove-discussion-labels:
    description: "Labels to remove before locking a discussion, value must be a comma separated list of labels"
    default: ""
  discussion-comment:
    description: "Comment to post before locking a discussion"
    default: >
      This discussion has been automatically locked since there
      has not been any recent activity after it was closed.
  process-only:
    description: "Only lock issues, pull requests or discussions, value must be a comma separated list, list items must be one of `issues`, `prs` or `discussions`"
    default: ""
  log-output:
    description: "Log output parameters, value must be either `true` or `false`"
    default: "true"

outputs:
  issues:
    description: "Issues that have been locked, value is a JSON string"
    value: ${{ steps.lock_threads.outputs.issues }}
  prs:
    description: "Pull requests that have been locked, value is a JSON string"
    value: ${{ steps.lock_threads.outputs.prs }}
  discussions:
    description: "Discussions that have been locked, value is a JSON string"
    value: ${{ steps.lock_threads.outputs.discussions }}

runs:
  using: "composite"
  steps:
    - name: Lock Threads
      uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5.0.1
      id: lock_threads
      with:
        github-token: ${{ inputs.github-token }}
        issue-inactive-days: "${{ inputs.issue-inactive-days }}"
        exclude-issue-created-before: "${{ inputs.exclude-issue-created-before }}"
        exclude-issue-created-after: "${{ inputs.exclude-issue-created-after }}"
        exclude-issue-created-between: "${{ inputs.exclude-issue-created-between }}"
        exclude-issue-closed-before: "${{ inputs.exclude-issue-closed-before }}"
        exclude-issue-closed-after: "${{ inputs.exclude-issue-closed-after }}"
        exclude-issue-closed-between: "${{ inputs.exclude-issue-closed-between }}"
        include-any-issue-labels: "${{ inputs.include-any-issue-labels }}"
        include-all-issue-labels: "${{ inputs.include-all-issue-labels }}"
        exclude-any-issue-labels: "${{ inputs.exclude-any-issue-labels }}"
        add-issue-labels: "${{ inputs.add-issue-labels }}"
        remove-issue-labels: "${{ inputs.remove-issue-labels }}"
        issue-comment: "${{ inputs.issue-comment }}"
        # issue-comment: >
        #   This issue has been automatically locked since there
        #   has not been any recent activity after it was closed.
        #   Please open a new issue for related bugs.
        issue-lock-reason: "${{ inputs.issue-lock-reason }}"
        pr-inactive-days: "${{ inputs.pr-inactive-days }}"
        exclude-pr-created-before: "${{ inputs.exclude-pr-created-before }}"
        exclude-pr-created-after: "${{ inputs.exclude-pr-created-after }}"
        exclude-pr-created-between: "${{ inputs.exclude-pr-created-between }}"
        exclude-pr-closed-before: "${{ inputs.exclude-pr-closed-before }}"
        exclude-pr-closed-after: "${{ inputs.exclude-pr-closed-after }}"
        exclude-pr-closed-between: "${{ inputs.exclude-pr-closed-between }}"
        include-any-pr-labels: "${{ inputs.include-any-pr-labels }}"
        include-all-pr-labels: "${{ inputs.include-all-pr-labels }}"
        exclude-any-pr-labels: "${{ inputs.exclude-any-pr-labels }}"
        add-pr-labels: "${{ inputs.add-pr-labels }}"
        remove-pr-labels: "${{ inputs.remove-pr-labels }}"
        pr-comment: "${{ inputs.pr-comment }}"
        # pr-comment: >
        #   This pull request has been automatically locked since there
        #   has not been any recent activity after it was closed.
        #   Please open a new issue for related bugs.
        pr-lock-reason: "${{ inputs.pr-lock-reason }}"
        discussion-inactive-days: "${{ inputs.discussion-inactive-days }}"
        exclude-discussion-created-before: "${{ inputs.exclude-discussion-created-before }}"
        exclude-discussion-created-after: "${{ inputs.exclude-discussion-created-after }}"
        exclude-discussion-created-between: "${{ inputs.exclude-discussion-created-between }}"
        exclude-discussion-closed-before: "${{ inputs.exclude-discussion-closed-before }}"
        exclude-discussion-closed-after: "${{ inputs.exclude-discussion-closed-after }}"
        exclude-discussion-closed-between: "${{ inputs.exclude-discussion-closed-between }}"
        include-any-discussion-labels: "${{ inputs.include-any-discussion-labels }}"
        include-all-discussion-labels: "${{ inputs.include-all-discussion-labels }}"
        exclude-any-discussion-labels: "${{ inputs.exclude-any-discussion-labels }}"
        add-discussion-labels: "${{ inputs.add-discussion-labels }}"
        remove-discussion-labels: "${{ inputs.remove-discussion-labels }}"
        discussion-comment: "${{ inputs.discussion-comment }}"
        # discussion-comment: >
        #   This discussion has been automatically locked since there
        #   has not been any recent activity after it was closed.
        process-only: "${{ inputs.process-only }}"
        log-output: ${{ inputs.log-output }}
