## Github workflow to generate a sha512 checksum for the build archive
name: Generate Checksum

inputs:
  arch:
    description: "Architecture to build binary for"
    required: true
    type: string
  tag:
    description: "Release Tag"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    ## Downloads the artifacts built in `create-source-binary.yml`
    - name: Download Artifacts
      id: download_artifacts
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: artifact
        path: release

    ## Generate a checksums file to be added to the release page
    - name: Generate Checksums
      id: generate_checksum
      shell: bash
      run: |
        if command -v sha512sum > /dev/null 2>&1; then
          echo "$(sha512sum release/*.zip > CHECKSUMS.txt)";
          exit 0;
        else
          echo "sha512sum command doesn't exist!";
          exit 1;
        fi
