name: Check Packages and Shards

outputs:
  run_big_packages: ${{ steps.check_packages_and_shards.outputs.run_big_packages }}
  big_packages_with_shards: ${{ steps.check_packages_and_shards.outputs.big_packages_with_shards }}
  run_small_packages: ${{ steps.check_packages_and_shards.outputs.run_small_packages }}
  small_packages_with_shards: ${{ steps.check_packages_and_shards.outputs.small_packages_with_shards }}

runs:
  using: "composite"

  steps:
    - name: Checkout stacks-core repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install cargo-mutants
      shell: bash
      run: cargo install --version 23.12.2 cargo-mutants

    - name: Relative diff
      shell: bash
      run: |
        git diff origin/${{ github.base_ref }}.. > git.diff

    - name: Update git diff
      shell: bash
      run: |
        input_file="git.diff"
        temp_file="temp_diff_file.diff"

        # Check if the commands exist on the host
        for cmd in tac awk sed; do
          command -v "${cmd}" > /dev/null 2>&1 || echo "Missing command: ${cmd}"
        done

        # Reverse the file, remove 4 lines after '+++ /dev/null', then reverse it back (editors can't go backwards - to remove lines above)
        tac "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
        sed '/+++ \/dev\/null/{n;N;N;N;d;}' "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
        tac "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"

        # Remove the lines between '+++ /dev/null' (included) and 'diff --git a/'
        awk '
          BEGIN { in_block=0 }
          /\+\+\+ \/dev\/null/ { in_block=1; next }
          in_block && /diff --git a\// { in_block=0; print; next }
          !in_block
        ' "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"

    - name: Split diffs
      shell: bash
      run: |
        cargo mutants --in-diff git.diff --list > all_mutants.txt
        mkdir -p mutants_by_packages

        # Check that the file exists before performing actions on it
        if [ -s all_mutants.txt ]; then
          echo "The file containing mutants is missing or empty!"
          exit 1
        fi

        # Split the differences from git into 2 parts, big packages ('stacks-node' and 'stackslib') and small packages (all others) and put them into separate files
        while IFS= read -r line; do
          package=$(echo "$line" | cut -d'/' -f1)
          if [[ $package == "testnet" || $package == "stackslib" ]]; then
            echo "$line" >> "mutants_by_packages/big_packages.txt"
          else
            echo "$line" >> "mutants_by_packages/small_packages.txt"
          fi
        done < all_mutants.txt

    - name: Check packages and shards
      id: check_packages_and_shards
      shell: bash
      run: |
        number_of_big_mutants=0
        number_of_small_mutants=0

        # If big_packages file exists, count how many mutants there are
        if [[ -s mutants_by_packages/big_packages.txt ]]; then
          number_of_big_mutants=$(cat mutants_by_packages/big_packages.txt | awk 'END { print NR }' | tr -d '[:space:]')
        fi

        # If small_packages file exists, count how many mutants there are
        if [[ -s mutants_by_packages/small_packages.txt ]]; then
          number_of_small_mutants=$(cat mutants_by_packages/small_packages.txt | awk 'END { print NR }' | tr -d '[:space:]')
        fi

        # Set the mutants limit for when to run with shards on the small packages
        if [[ $number_of_big_mutants -gt 15 ]]; then
          small_packages_shard_limit=119
        else
          small_packages_shard_limit=79
        fi

        # If there are mutants from big packages, check whether to run with or without shards, otherwise there's nothing to run
        if [[ $number_of_big_mutants -ne 0 ]]; then
          echo "run_big_packages=true" >> "$GITHUB_OUTPUT"
          if [[ $number_of_big_mutants -gt 15 ]]; then
            echo "big_packages_with_shards=true" >> "$GITHUB_OUTPUT"
          else
            echo "big_packages_with_shards=false" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "run_big_packages=false" >> "$GITHUB_OUTPUT"
        fi

        # If there are mutants from small packages, check whether to run with or without shards, otherwise there's nothing to run
        if [[ $number_of_small_mutants -ne 0 ]]; then
          echo "run_small_packages=true" >> "$GITHUB_OUTPUT"
          if [[ $number_of_small_mutants -gt $small_packages_shard_limit ]]; then
            echo "small_packages_with_shards=true" >> "$GITHUB_OUTPUT"
          else
            echo "small_packages_with_shards=false" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "run_small_packages=false" >> "$GITHUB_OUTPUT"
        fi
