name: "Test actions"

runs:
  using: "composite"
  steps:
    ## cleanup runner
    - name: Cleanup Runner action repo
      id: runner_cleanup
      uses: wileyj/actions/cleanup/disk@main

    ## Checkout the code
    - name: Checkout the latest code action repo
      id: git_checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Print root files action repo
      shell: bash
      run: |
        ls ./
