name: Upload initial cache

runs:
  using: "composite"

  steps:
    # Checkout the stacks-core code
    - name: Checkout the stacks core repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create file with current commit hash if it doesn't exist
      shell: bash
      run: |
        if [ ! -f last_commit_hash.txt ]; then
          echo "${{ github.sha }}" > last_commit_hash.txt
        fi
      working-directory: ./mutation-testing/packages-output

    - name: Print old commit hash
      shell: bash
      run: cat ./mutation-testing/packages-output/last_commit_hash.txt

    # TODO: feature for retrying the save in case it fails for any reason (in order not to lose the cache)
    - name: Save Cache
      uses: actions/cache/save@v3
      with:
        path: ./mutation-testing/packages-output
        key: mutants-stable-${{ github.ref_name }}
