name: Filter PR Mutants

inputs:
  shard:
    description: "The number of the shard to run"
    required: true

runs:
  using: "composite"

  steps:
    # Cleanup Runner
    - name: Cleanup Runner action repo
      id: runner_cleanup
      uses: stacks-network/actions/cleanup/disk@main

    # Checkout the stacks-core code
    - name: Checkout the stacks core repo
      id: git_checkout_stacks_core
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Relative diff
      shell: bash
      run: |
        git diff origin/${{ github.base_ref }}.. > git.diff

    # Checkout the actions code
    - name: Get the action repo code
      id: git_checkout_actions
      uses: actions/checkout@v3
      with:
        repository: ASuciuX/actions
        ref: test/simulate-pr-and-merged-mutants
        path: ./actions-repo

    - name: Copy the git diff file to scripts folder
      shell: bash
      run: |
        mv git.diff ./actions-repo/mutation-testing/shell-scripts/

    - name: Install cargo mutants crate
      shell: bash
      run: cargo install --git https://github.com/sourcefrog/cargo-mutants cargo-mutants

    - name: Remove deleted file lines from git.diff file
      shell: bash
      run: ./remove-deleted-file-lines.sh
      working-directory: actions-repo/mutation-testing/shell-scripts

    - name: Run mutants and check the exit code of the command, fail the workflow if mutations are not caught
      shell: bash
      run: |
        set +e  # Disable immediate exit on error
        BITCOIND_TEST=1 RUST_BACKTRACE=full cargo mutants --no-shuffle -j 2 -vV --in-diff git.diff --shard ${{ inputs.shard }}/16 --output ./ -- -- --test-threads 1
        exit_code=$?
        mkdir mutants-shard-${{ inputs.shard }}
        echo "$exit_code" > ./mutants-shard-${{ inputs.shard }}/exit_code.txt
        mv ./mutants.out/*.txt mutants-shard-${{ inputs.shard }}/
        set -e  # Enable immediate exit on error again
      working-directory: actions-repo/mutation-testing/shell-scripts

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: mutants-shard-${{ inputs.shard }}
        path: actions-repo/mutation-testing/shell-scripts/mutants-shard-${{ inputs.shard }}
